# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
podfile: Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install
script:
- set -o pipefail && xcodebuild test -workspace SimPermissions.xcworkspace -scheme SimPermissions -sdk macosx10.11 ONLY_ACTIVE_ARCH=NO | xcpretty
